package com.tapi.a0028speedtest.util

object Constances {

    val SETTING_SCREEN_MBP_VALUE_1 = "100"
    val SETTING_SCREEN_MBP_VALUE_2 = "500"
    val SETTING_SCREEN_MBP_VALUE_3 = "1000"

    val SETTING_SCREEN_MB_VALUE_1 = "10"
    val SETTING_SCREEN_MB_VALUE_2 = "50"
    val SETTING_SCREEN_MB_VALUE_3 = "100"

    val SETTING_SCREEN_KB_VALUE_1 = "5000"
    val SETTING_SCREEN_KB_VALUE_2 = "10000"
    val SETTING_SCREEN_KB_VALUE_3 = "15000"


}